/* 
 * Docusign Admin API
 *
 * An API for an organization administrator to manage organizations, accounts and users
 *
 * OpenAPI spec version: v2.1
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Admin.Model
{
    /// <summary>
    /// ConnectEventData
    /// </summary>
    [DataContract]
    public partial class ConnectEventData :  IEquatable<ConnectEventData>, IValidatableObject
    {
        public ConnectEventData()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectEventData" /> class.
        /// </summary>
        /// <param name="Version">Version.</param>
        /// <param name="IncludeData">IncludeData.</param>
        public ConnectEventData(string Version = default(string), List<string> IncludeData = default(List<string>))
        {
            this.Version = Version;
            this.IncludeData = IncludeData;
        }
        
        /// <summary>
        /// Gets or Sets Version
        /// </summary>
        [DataMember(Name="version", EmitDefaultValue=false)]
        public string Version { get; set; }
        /// <summary>
        /// Gets or Sets IncludeData
        /// </summary>
        [DataMember(Name="includeData", EmitDefaultValue=false)]
        public List<string> IncludeData { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConnectEventData {\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("  IncludeData: ").Append(IncludeData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ConnectEventData);
        }

        /// <summary>
        /// Returns true if ConnectEventData instances are equal
        /// </summary>
        /// <param name="other">Instance of ConnectEventData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConnectEventData other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Version == other.Version ||
                    this.Version != null &&
                    this.Version.Equals(other.Version)
                ) && 
                (
                    this.IncludeData == other.IncludeData ||
                    this.IncludeData != null &&
                    this.IncludeData.SequenceEqual(other.IncludeData)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Version != null)
                    hash = hash * 59 + this.Version.GetHashCode();
                if (this.IncludeData != null)
                    hash = hash * 59 + this.IncludeData.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
