/* 
 * Docusign Admin API
 *
 * An API for an organization administrator to manage organizations, accounts and users
 *
 * OpenAPI spec version: v2.1
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Admin.Model
{
    /// <summary>
    /// OrganizationConnectConfigurationDetailsResponse
    /// </summary>
    [DataContract]
    public partial class OrganizationConnectConfigurationDetailsResponse :  IEquatable<OrganizationConnectConfigurationDetailsResponse>, IValidatableObject
    {
        public OrganizationConnectConfigurationDetailsResponse()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizationConnectConfigurationDetailsResponse" /> class.
        /// </summary>
        /// <param name="ConnectId">ConnectId.</param>
        /// <param name="ConfigurationType">ConfigurationType.</param>
        /// <param name="AllowEnvelopePublish">AllowEnvelopePublish.</param>
        /// <param name="UrlToPublishTo">UrlToPublishTo.</param>
        /// <param name="DeliveryMode">DeliveryMode.</param>
        /// <param name="Events">Events.</param>
        /// <param name="AssociatedFilterSelection">AssociatedFilterSelection.</param>
        /// <param name="AccountIds">AccountIds.</param>
        /// <param name="UserIds">UserIds.</param>
        /// <param name="GroupIds">GroupIds.</param>
        /// <param name="Name">Name.</param>
        /// <param name="SignMessageWithX509Certificate">SignMessageWithX509Certificate.</param>
        /// <param name="IncludeOAuth">IncludeOAuth.</param>
        /// <param name="IncludeHMAC">IncludeHMAC.</param>
        /// <param name="PausePublish">PausePublish.</param>
        /// <param name="EventData">EventData.</param>
        public OrganizationConnectConfigurationDetailsResponse(Guid? ConnectId = default(Guid?), string ConfigurationType = default(string), string AllowEnvelopePublish = default(string), string UrlToPublishTo = default(string), string DeliveryMode = default(string), List<string> Events = default(List<string>), string AssociatedFilterSelection = default(string), List<string> AccountIds = default(List<string>), List<string> UserIds = default(List<string>), List<string> GroupIds = default(List<string>), string Name = default(string), string SignMessageWithX509Certificate = default(string), string IncludeOAuth = default(string), string IncludeHMAC = default(string), string PausePublish = default(string), ConnectEventData EventData = default(ConnectEventData))
        {
            this.ConnectId = ConnectId;
            this.ConfigurationType = ConfigurationType;
            this.AllowEnvelopePublish = AllowEnvelopePublish;
            this.UrlToPublishTo = UrlToPublishTo;
            this.DeliveryMode = DeliveryMode;
            this.Events = Events;
            this.AssociatedFilterSelection = AssociatedFilterSelection;
            this.AccountIds = AccountIds;
            this.UserIds = UserIds;
            this.GroupIds = GroupIds;
            this.Name = Name;
            this.SignMessageWithX509Certificate = SignMessageWithX509Certificate;
            this.IncludeOAuth = IncludeOAuth;
            this.IncludeHMAC = IncludeHMAC;
            this.PausePublish = PausePublish;
            this.EventData = EventData;
        }
        
        /// <summary>
        /// Gets or Sets ConnectId
        /// </summary>
        [DataMember(Name="connectId", EmitDefaultValue=false)]
        public Guid? ConnectId { get; set; }
        /// <summary>
        /// Gets or Sets ConfigurationType
        /// </summary>
        [DataMember(Name="configurationType", EmitDefaultValue=false)]
        public string ConfigurationType { get; set; }
        /// <summary>
        /// Gets or Sets AllowEnvelopePublish
        /// </summary>
        [DataMember(Name="allowEnvelopePublish", EmitDefaultValue=false)]
        public string AllowEnvelopePublish { get; set; }
        /// <summary>
        /// Gets or Sets UrlToPublishTo
        /// </summary>
        [DataMember(Name="urlToPublishTo", EmitDefaultValue=false)]
        public string UrlToPublishTo { get; set; }
        /// <summary>
        /// Gets or Sets DeliveryMode
        /// </summary>
        [DataMember(Name="deliveryMode", EmitDefaultValue=false)]
        public string DeliveryMode { get; set; }
        /// <summary>
        /// Gets or Sets Events
        /// </summary>
        [DataMember(Name="events", EmitDefaultValue=false)]
        public List<string> Events { get; set; }
        /// <summary>
        /// Gets or Sets AssociatedFilterSelection
        /// </summary>
        [DataMember(Name="associatedFilterSelection", EmitDefaultValue=false)]
        public string AssociatedFilterSelection { get; set; }
        /// <summary>
        /// Gets or Sets AccountIds
        /// </summary>
        [DataMember(Name="accountIds", EmitDefaultValue=false)]
        public List<string> AccountIds { get; set; }
        /// <summary>
        /// Gets or Sets UserIds
        /// </summary>
        [DataMember(Name="userIds", EmitDefaultValue=false)]
        public List<string> UserIds { get; set; }
        /// <summary>
        /// Gets or Sets GroupIds
        /// </summary>
        [DataMember(Name="groupIds", EmitDefaultValue=false)]
        public List<string> GroupIds { get; set; }
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// Gets or Sets SignMessageWithX509Certificate
        /// </summary>
        [DataMember(Name="signMessageWithX509Certificate", EmitDefaultValue=false)]
        public string SignMessageWithX509Certificate { get; set; }
        /// <summary>
        /// Gets or Sets IncludeOAuth
        /// </summary>
        [DataMember(Name="includeOAuth", EmitDefaultValue=false)]
        public string IncludeOAuth { get; set; }
        /// <summary>
        /// Gets or Sets IncludeHMAC
        /// </summary>
        [DataMember(Name="includeHMAC", EmitDefaultValue=false)]
        public string IncludeHMAC { get; set; }
        /// <summary>
        /// Gets or Sets PausePublish
        /// </summary>
        [DataMember(Name="pausePublish", EmitDefaultValue=false)]
        public string PausePublish { get; set; }
        /// <summary>
        /// Gets or Sets EventData
        /// </summary>
        [DataMember(Name="eventData", EmitDefaultValue=false)]
        public ConnectEventData EventData { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrganizationConnectConfigurationDetailsResponse {\n");
            sb.Append("  ConnectId: ").Append(ConnectId).Append("\n");
            sb.Append("  ConfigurationType: ").Append(ConfigurationType).Append("\n");
            sb.Append("  AllowEnvelopePublish: ").Append(AllowEnvelopePublish).Append("\n");
            sb.Append("  UrlToPublishTo: ").Append(UrlToPublishTo).Append("\n");
            sb.Append("  DeliveryMode: ").Append(DeliveryMode).Append("\n");
            sb.Append("  Events: ").Append(Events).Append("\n");
            sb.Append("  AssociatedFilterSelection: ").Append(AssociatedFilterSelection).Append("\n");
            sb.Append("  AccountIds: ").Append(AccountIds).Append("\n");
            sb.Append("  UserIds: ").Append(UserIds).Append("\n");
            sb.Append("  GroupIds: ").Append(GroupIds).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  SignMessageWithX509Certificate: ").Append(SignMessageWithX509Certificate).Append("\n");
            sb.Append("  IncludeOAuth: ").Append(IncludeOAuth).Append("\n");
            sb.Append("  IncludeHMAC: ").Append(IncludeHMAC).Append("\n");
            sb.Append("  PausePublish: ").Append(PausePublish).Append("\n");
            sb.Append("  EventData: ").Append(EventData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as OrganizationConnectConfigurationDetailsResponse);
        }

        /// <summary>
        /// Returns true if OrganizationConnectConfigurationDetailsResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of OrganizationConnectConfigurationDetailsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrganizationConnectConfigurationDetailsResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ConnectId == other.ConnectId ||
                    this.ConnectId != null &&
                    this.ConnectId.Equals(other.ConnectId)
                ) && 
                (
                    this.ConfigurationType == other.ConfigurationType ||
                    this.ConfigurationType != null &&
                    this.ConfigurationType.Equals(other.ConfigurationType)
                ) && 
                (
                    this.AllowEnvelopePublish == other.AllowEnvelopePublish ||
                    this.AllowEnvelopePublish != null &&
                    this.AllowEnvelopePublish.Equals(other.AllowEnvelopePublish)
                ) && 
                (
                    this.UrlToPublishTo == other.UrlToPublishTo ||
                    this.UrlToPublishTo != null &&
                    this.UrlToPublishTo.Equals(other.UrlToPublishTo)
                ) && 
                (
                    this.DeliveryMode == other.DeliveryMode ||
                    this.DeliveryMode != null &&
                    this.DeliveryMode.Equals(other.DeliveryMode)
                ) && 
                (
                    this.Events == other.Events ||
                    this.Events != null &&
                    this.Events.SequenceEqual(other.Events)
                ) && 
                (
                    this.AssociatedFilterSelection == other.AssociatedFilterSelection ||
                    this.AssociatedFilterSelection != null &&
                    this.AssociatedFilterSelection.Equals(other.AssociatedFilterSelection)
                ) && 
                (
                    this.AccountIds == other.AccountIds ||
                    this.AccountIds != null &&
                    this.AccountIds.SequenceEqual(other.AccountIds)
                ) && 
                (
                    this.UserIds == other.UserIds ||
                    this.UserIds != null &&
                    this.UserIds.SequenceEqual(other.UserIds)
                ) && 
                (
                    this.GroupIds == other.GroupIds ||
                    this.GroupIds != null &&
                    this.GroupIds.SequenceEqual(other.GroupIds)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.SignMessageWithX509Certificate == other.SignMessageWithX509Certificate ||
                    this.SignMessageWithX509Certificate != null &&
                    this.SignMessageWithX509Certificate.Equals(other.SignMessageWithX509Certificate)
                ) && 
                (
                    this.IncludeOAuth == other.IncludeOAuth ||
                    this.IncludeOAuth != null &&
                    this.IncludeOAuth.Equals(other.IncludeOAuth)
                ) && 
                (
                    this.IncludeHMAC == other.IncludeHMAC ||
                    this.IncludeHMAC != null &&
                    this.IncludeHMAC.Equals(other.IncludeHMAC)
                ) && 
                (
                    this.PausePublish == other.PausePublish ||
                    this.PausePublish != null &&
                    this.PausePublish.Equals(other.PausePublish)
                ) && 
                (
                    this.EventData == other.EventData ||
                    this.EventData != null &&
                    this.EventData.Equals(other.EventData)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ConnectId != null)
                    hash = hash * 59 + this.ConnectId.GetHashCode();
                if (this.ConfigurationType != null)
                    hash = hash * 59 + this.ConfigurationType.GetHashCode();
                if (this.AllowEnvelopePublish != null)
                    hash = hash * 59 + this.AllowEnvelopePublish.GetHashCode();
                if (this.UrlToPublishTo != null)
                    hash = hash * 59 + this.UrlToPublishTo.GetHashCode();
                if (this.DeliveryMode != null)
                    hash = hash * 59 + this.DeliveryMode.GetHashCode();
                if (this.Events != null)
                    hash = hash * 59 + this.Events.GetHashCode();
                if (this.AssociatedFilterSelection != null)
                    hash = hash * 59 + this.AssociatedFilterSelection.GetHashCode();
                if (this.AccountIds != null)
                    hash = hash * 59 + this.AccountIds.GetHashCode();
                if (this.UserIds != null)
                    hash = hash * 59 + this.UserIds.GetHashCode();
                if (this.GroupIds != null)
                    hash = hash * 59 + this.GroupIds.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.SignMessageWithX509Certificate != null)
                    hash = hash * 59 + this.SignMessageWithX509Certificate.GetHashCode();
                if (this.IncludeOAuth != null)
                    hash = hash * 59 + this.IncludeOAuth.GetHashCode();
                if (this.IncludeHMAC != null)
                    hash = hash * 59 + this.IncludeHMAC.GetHashCode();
                if (this.PausePublish != null)
                    hash = hash * 59 + this.PausePublish.GetHashCode();
                if (this.EventData != null)
                    hash = hash * 59 + this.EventData.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
