/* 
 * Docusign Admin API
 *
 * An API for an organization administrator to manage organizations, accounts and users
 *
 * OpenAPI spec version: v2.1
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Admin.Model
{
    /// <summary>
    /// OrganizationConnectConfigResponse
    /// </summary>
    [DataContract]
    public partial class OrganizationConnectConfigResponse :  IEquatable<OrganizationConnectConfigResponse>, IValidatableObject
    {
        public OrganizationConnectConfigResponse()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizationConnectConfigResponse" /> class.
        /// </summary>
        /// <param name="ConnectId">ConnectId.</param>
        /// <param name="ConfigurationType">ConfigurationType.</param>
        /// <param name="DisabledBy">DisabledBy.</param>
        /// <param name="AllowSalesforcePublish">AllowSalesforcePublish.</param>
        /// <param name="Name">Name.</param>
        /// <param name="AccountId">AccountId.</param>
        /// <param name="AccountName">AccountName.</param>
        /// <param name="AllowEnvelopePublish">AllowEnvelopePublish.</param>
        /// <param name="SiteId">SiteId.</param>
        /// <param name="PausePublish">PausePublish.</param>
        /// <param name="RequiresAcknowledgement">RequiresAcknowledgement.</param>
        public OrganizationConnectConfigResponse(string ConnectId = default(string), string ConfigurationType = default(string), string DisabledBy = default(string), string AllowSalesforcePublish = default(string), string Name = default(string), string AccountId = default(string), string AccountName = default(string), string AllowEnvelopePublish = default(string), int? SiteId = default(int?), string PausePublish = default(string), string RequiresAcknowledgement = default(string))
        {
            this.ConnectId = ConnectId;
            this.ConfigurationType = ConfigurationType;
            this.DisabledBy = DisabledBy;
            this.AllowSalesforcePublish = AllowSalesforcePublish;
            this.Name = Name;
            this.AccountId = AccountId;
            this.AccountName = AccountName;
            this.AllowEnvelopePublish = AllowEnvelopePublish;
            this.SiteId = SiteId;
            this.PausePublish = PausePublish;
            this.RequiresAcknowledgement = RequiresAcknowledgement;
        }
        
        /// <summary>
        /// Gets or Sets ConnectId
        /// </summary>
        [DataMember(Name="connectId", EmitDefaultValue=false)]
        public string ConnectId { get; set; }
        /// <summary>
        /// Gets or Sets ConfigurationType
        /// </summary>
        [DataMember(Name="configurationType", EmitDefaultValue=false)]
        public string ConfigurationType { get; set; }
        /// <summary>
        /// Gets or Sets DisabledBy
        /// </summary>
        [DataMember(Name="disabledBy", EmitDefaultValue=false)]
        public string DisabledBy { get; set; }
        /// <summary>
        /// Gets or Sets AllowSalesforcePublish
        /// </summary>
        [DataMember(Name="allowSalesforcePublish", EmitDefaultValue=false)]
        public string AllowSalesforcePublish { get; set; }
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name="accountId", EmitDefaultValue=false)]
        public string AccountId { get; set; }
        /// <summary>
        /// Gets or Sets AccountName
        /// </summary>
        [DataMember(Name="accountName", EmitDefaultValue=false)]
        public string AccountName { get; set; }
        /// <summary>
        /// Gets or Sets AllowEnvelopePublish
        /// </summary>
        [DataMember(Name="allowEnvelopePublish", EmitDefaultValue=false)]
        public string AllowEnvelopePublish { get; set; }
        /// <summary>
        /// Gets or Sets SiteId
        /// </summary>
        [DataMember(Name="siteId", EmitDefaultValue=false)]
        public int? SiteId { get; set; }
        /// <summary>
        /// Gets or Sets PausePublish
        /// </summary>
        [DataMember(Name="pausePublish", EmitDefaultValue=false)]
        public string PausePublish { get; set; }
        /// <summary>
        /// Gets or Sets RequiresAcknowledgement
        /// </summary>
        [DataMember(Name="requiresAcknowledgement", EmitDefaultValue=false)]
        public string RequiresAcknowledgement { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrganizationConnectConfigResponse {\n");
            sb.Append("  ConnectId: ").Append(ConnectId).Append("\n");
            sb.Append("  ConfigurationType: ").Append(ConfigurationType).Append("\n");
            sb.Append("  DisabledBy: ").Append(DisabledBy).Append("\n");
            sb.Append("  AllowSalesforcePublish: ").Append(AllowSalesforcePublish).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  AccountName: ").Append(AccountName).Append("\n");
            sb.Append("  AllowEnvelopePublish: ").Append(AllowEnvelopePublish).Append("\n");
            sb.Append("  SiteId: ").Append(SiteId).Append("\n");
            sb.Append("  PausePublish: ").Append(PausePublish).Append("\n");
            sb.Append("  RequiresAcknowledgement: ").Append(RequiresAcknowledgement).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as OrganizationConnectConfigResponse);
        }

        /// <summary>
        /// Returns true if OrganizationConnectConfigResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of OrganizationConnectConfigResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrganizationConnectConfigResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ConnectId == other.ConnectId ||
                    this.ConnectId != null &&
                    this.ConnectId.Equals(other.ConnectId)
                ) && 
                (
                    this.ConfigurationType == other.ConfigurationType ||
                    this.ConfigurationType != null &&
                    this.ConfigurationType.Equals(other.ConfigurationType)
                ) && 
                (
                    this.DisabledBy == other.DisabledBy ||
                    this.DisabledBy != null &&
                    this.DisabledBy.Equals(other.DisabledBy)
                ) && 
                (
                    this.AllowSalesforcePublish == other.AllowSalesforcePublish ||
                    this.AllowSalesforcePublish != null &&
                    this.AllowSalesforcePublish.Equals(other.AllowSalesforcePublish)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.AccountId == other.AccountId ||
                    this.AccountId != null &&
                    this.AccountId.Equals(other.AccountId)
                ) && 
                (
                    this.AccountName == other.AccountName ||
                    this.AccountName != null &&
                    this.AccountName.Equals(other.AccountName)
                ) && 
                (
                    this.AllowEnvelopePublish == other.AllowEnvelopePublish ||
                    this.AllowEnvelopePublish != null &&
                    this.AllowEnvelopePublish.Equals(other.AllowEnvelopePublish)
                ) && 
                (
                    this.SiteId == other.SiteId ||
                    this.SiteId != null &&
                    this.SiteId.Equals(other.SiteId)
                ) && 
                (
                    this.PausePublish == other.PausePublish ||
                    this.PausePublish != null &&
                    this.PausePublish.Equals(other.PausePublish)
                ) && 
                (
                    this.RequiresAcknowledgement == other.RequiresAcknowledgement ||
                    this.RequiresAcknowledgement != null &&
                    this.RequiresAcknowledgement.Equals(other.RequiresAcknowledgement)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ConnectId != null)
                    hash = hash * 59 + this.ConnectId.GetHashCode();
                if (this.ConfigurationType != null)
                    hash = hash * 59 + this.ConfigurationType.GetHashCode();
                if (this.DisabledBy != null)
                    hash = hash * 59 + this.DisabledBy.GetHashCode();
                if (this.AllowSalesforcePublish != null)
                    hash = hash * 59 + this.AllowSalesforcePublish.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.AccountId != null)
                    hash = hash * 59 + this.AccountId.GetHashCode();
                if (this.AccountName != null)
                    hash = hash * 59 + this.AccountName.GetHashCode();
                if (this.AllowEnvelopePublish != null)
                    hash = hash * 59 + this.AllowEnvelopePublish.GetHashCode();
                if (this.SiteId != null)
                    hash = hash * 59 + this.SiteId.GetHashCode();
                if (this.PausePublish != null)
                    hash = hash * 59 + this.PausePublish.GetHashCode();
                if (this.RequiresAcknowledgement != null)
                    hash = hash * 59 + this.RequiresAcknowledgement.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
