/* 
 * DocuSign Admin API
 *
 * An API for an organization administrator to manage organizations, accounts and users
 *
 * OpenAPI spec version: v2.1
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Admin.Model
{
    /// <summary>
    /// OrganizationExportsResponse
    /// </summary>
    [DataContract]
    public partial class OrganizationExportsResponse :  IEquatable<OrganizationExportsResponse>, IValidatableObject
    {
        public OrganizationExportsResponse()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizationExportsResponse" /> class.
        /// </summary>
        /// <param name="Exports">Exports.</param>
        public OrganizationExportsResponse(List<OrganizationExportResponse> Exports = default(List<OrganizationExportResponse>))
        {
            this.Exports = Exports;
        }
        
        /// <summary>
        /// Gets or Sets Exports
        /// </summary>
        [DataMember(Name="exports", EmitDefaultValue=false)]
        public List<OrganizationExportResponse> Exports { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrganizationExportsResponse {\n");
            sb.Append("  Exports: ").Append(Exports).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as OrganizationExportsResponse);
        }

        /// <summary>
        /// Returns true if OrganizationExportsResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of OrganizationExportsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrganizationExportsResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Exports == other.Exports ||
                    this.Exports != null &&
                    this.Exports.SequenceEqual(other.Exports)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Exports != null)
                    hash = hash * 59 + this.Exports.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
