/* 
 * Docusign Admin API
 *
 * An API for an organization administrator to manage organizations, accounts and users
 *
 * OpenAPI spec version: v2.1
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Admin.Model
{
    /// <summary>
    /// OrgReportCreateResponse
    /// </summary>
    [DataContract]
    public partial class OrgReportCreateResponse :  IEquatable<OrgReportCreateResponse>, IValidatableObject
    {
        public OrgReportCreateResponse()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrgReportCreateResponse" /> class.
        /// </summary>
        /// <param name="ReportCorrelationId">ReportCorrelationId.</param>
        public OrgReportCreateResponse(Guid? ReportCorrelationId = default(Guid?))
        {
            this.ReportCorrelationId = ReportCorrelationId;
        }
        
        /// <summary>
        /// Gets or Sets ReportCorrelationId
        /// </summary>
        [DataMember(Name="report_correlation_id", EmitDefaultValue=false)]
        public Guid? ReportCorrelationId { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrgReportCreateResponse {\n");
            sb.Append("  ReportCorrelationId: ").Append(ReportCorrelationId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as OrgReportCreateResponse);
        }

        /// <summary>
        /// Returns true if OrgReportCreateResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of OrgReportCreateResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrgReportCreateResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ReportCorrelationId == other.ReportCorrelationId ||
                    this.ReportCorrelationId != null &&
                    this.ReportCorrelationId.Equals(other.ReportCorrelationId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ReportCorrelationId != null)
                    hash = hash * 59 + this.ReportCorrelationId.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
