/* 
 * Docusign Admin API
 *
 * An API for an organization administrator to manage organizations, accounts and users
 *
 * OpenAPI spec version: v2.1
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Admin.Model
{
    /// <summary>
    /// SubAccountCreateRequest
    /// </summary>
    [DataContract]
    public partial class SubAccountCreateRequest :  IEquatable<SubAccountCreateRequest>, IValidatableObject
    {
        public SubAccountCreateRequest()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SubAccountCreateRequest" /> class.
        /// </summary>
        /// <param name="SubscriptionDetails">SubscriptionDetails.</param>
        /// <param name="TargetAccount">TargetAccount.</param>
        public SubAccountCreateRequest(SubAccountCreateRequestSubAccountCreationSubscription SubscriptionDetails = default(SubAccountCreateRequestSubAccountCreationSubscription), SubAccountCreateRequestSubAccountCreationTargetAccountDetails TargetAccount = default(SubAccountCreateRequestSubAccountCreationTargetAccountDetails))
        {
            this.SubscriptionDetails = SubscriptionDetails;
            this.TargetAccount = TargetAccount;
        }
        
        /// <summary>
        /// Gets or Sets SubscriptionDetails
        /// </summary>
        [DataMember(Name="subscriptionDetails", EmitDefaultValue=false)]
        public SubAccountCreateRequestSubAccountCreationSubscription SubscriptionDetails { get; set; }
        /// <summary>
        /// Gets or Sets TargetAccount
        /// </summary>
        [DataMember(Name="targetAccount", EmitDefaultValue=false)]
        public SubAccountCreateRequestSubAccountCreationTargetAccountDetails TargetAccount { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubAccountCreateRequest {\n");
            sb.Append("  SubscriptionDetails: ").Append(SubscriptionDetails).Append("\n");
            sb.Append("  TargetAccount: ").Append(TargetAccount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as SubAccountCreateRequest);
        }

        /// <summary>
        /// Returns true if SubAccountCreateRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of SubAccountCreateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubAccountCreateRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.SubscriptionDetails == other.SubscriptionDetails ||
                    this.SubscriptionDetails != null &&
                    this.SubscriptionDetails.Equals(other.SubscriptionDetails)
                ) && 
                (
                    this.TargetAccount == other.TargetAccount ||
                    this.TargetAccount != null &&
                    this.TargetAccount.Equals(other.TargetAccount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.SubscriptionDetails != null)
                    hash = hash * 59 + this.SubscriptionDetails.GetHashCode();
                if (this.TargetAccount != null)
                    hash = hash * 59 + this.TargetAccount.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
