/* 
 * Docusign Admin API
 *
 * An API for an organization administrator to manage organizations, accounts and users
 *
 * OpenAPI spec version: v2.1
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Admin.Model
{
    /// <summary>
    /// SubscriptionProvisionModelAssetGroupWorkResult
    /// </summary>
    [DataContract]
    public partial class SubscriptionProvisionModelAssetGroupWorkResult :  IEquatable<SubscriptionProvisionModelAssetGroupWorkResult>, IValidatableObject
    {
        public SubscriptionProvisionModelAssetGroupWorkResult()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionProvisionModelAssetGroupWorkResult" /> class.
        /// </summary>
        /// <param name="AssetGroupWork">AssetGroupWork.</param>
        public SubscriptionProvisionModelAssetGroupWorkResult(SubscriptionProvisionModelAssetGroupWork AssetGroupWork = default(SubscriptionProvisionModelAssetGroupWork))
        {
            this.AssetGroupWork = AssetGroupWork;
        }
        
        /// <summary>
        /// Gets or Sets AssetGroupWork
        /// </summary>
        [DataMember(Name="AssetGroupWork", EmitDefaultValue=false)]
        public SubscriptionProvisionModelAssetGroupWork AssetGroupWork { get; set; }
        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name="Message", EmitDefaultValue=false)]
        public string Message { get; private set; }
        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name="Success", EmitDefaultValue=false)]
        public bool? Success { get; private set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubscriptionProvisionModelAssetGroupWorkResult {\n");
            sb.Append("  AssetGroupWork: ").Append(AssetGroupWork).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as SubscriptionProvisionModelAssetGroupWorkResult);
        }

        /// <summary>
        /// Returns true if SubscriptionProvisionModelAssetGroupWorkResult instances are equal
        /// </summary>
        /// <param name="other">Instance of SubscriptionProvisionModelAssetGroupWorkResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubscriptionProvisionModelAssetGroupWorkResult other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.AssetGroupWork == other.AssetGroupWork ||
                    this.AssetGroupWork != null &&
                    this.AssetGroupWork.Equals(other.AssetGroupWork)
                ) && 
                (
                    this.Message == other.Message ||
                    this.Message != null &&
                    this.Message.Equals(other.Message)
                ) && 
                (
                    this.Success == other.Success ||
                    this.Success != null &&
                    this.Success.Equals(other.Success)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.AssetGroupWork != null)
                    hash = hash * 59 + this.AssetGroupWork.GetHashCode();
                if (this.Message != null)
                    hash = hash * 59 + this.Message.GetHashCode();
                if (this.Success != null)
                    hash = hash * 59 + this.Success.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
