/* 
 * Docusign Admin API
 *
 * An API for an organization administrator to manage organizations, accounts and users
 *
 * OpenAPI spec version: v2.1
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.Admin.Model
{
    /// <summary>
    /// SubscriptionProvisionModelServiceErrorDetails
    /// </summary>
    [DataContract]
    public partial class SubscriptionProvisionModelServiceErrorDetails :  IEquatable<SubscriptionProvisionModelServiceErrorDetails>, IValidatableObject
    {
        public SubscriptionProvisionModelServiceErrorDetails()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionProvisionModelServiceErrorDetails" /> class.
        /// </summary>
        /// <param name="ErrorCode">ErrorCode.</param>
        /// <param name="PublicErrorCode">PublicErrorCode.</param>
        /// <param name="ErrorDescription">ErrorDescription.</param>
        /// <param name="IsSystemError">IsSystemError.</param>
        public SubscriptionProvisionModelServiceErrorDetails(string ErrorCode = default(string), string PublicErrorCode = default(string), string ErrorDescription = default(string), bool? IsSystemError = default(bool?))
        {
            this.ErrorCode = ErrorCode;
            this.PublicErrorCode = PublicErrorCode;
            this.ErrorDescription = ErrorDescription;
            this.IsSystemError = IsSystemError;
        }
        
        /// <summary>
        /// Gets or Sets ErrorCode
        /// </summary>
        [DataMember(Name="ErrorCode", EmitDefaultValue=false)]
        public string ErrorCode { get; set; }
        /// <summary>
        /// Gets or Sets PublicErrorCode
        /// </summary>
        [DataMember(Name="PublicErrorCode", EmitDefaultValue=false)]
        public string PublicErrorCode { get; set; }
        /// <summary>
        /// Gets or Sets ErrorDescription
        /// </summary>
        [DataMember(Name="ErrorDescription", EmitDefaultValue=false)]
        public string ErrorDescription { get; set; }
        /// <summary>
        /// Gets or Sets IsSystemError
        /// </summary>
        [DataMember(Name="IsSystemError", EmitDefaultValue=false)]
        public bool? IsSystemError { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubscriptionProvisionModelServiceErrorDetails {\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("  PublicErrorCode: ").Append(PublicErrorCode).Append("\n");
            sb.Append("  ErrorDescription: ").Append(ErrorDescription).Append("\n");
            sb.Append("  IsSystemError: ").Append(IsSystemError).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as SubscriptionProvisionModelServiceErrorDetails);
        }

        /// <summary>
        /// Returns true if SubscriptionProvisionModelServiceErrorDetails instances are equal
        /// </summary>
        /// <param name="other">Instance of SubscriptionProvisionModelServiceErrorDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubscriptionProvisionModelServiceErrorDetails other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ErrorCode == other.ErrorCode ||
                    this.ErrorCode != null &&
                    this.ErrorCode.Equals(other.ErrorCode)
                ) && 
                (
                    this.PublicErrorCode == other.PublicErrorCode ||
                    this.PublicErrorCode != null &&
                    this.PublicErrorCode.Equals(other.PublicErrorCode)
                ) && 
                (
                    this.ErrorDescription == other.ErrorDescription ||
                    this.ErrorDescription != null &&
                    this.ErrorDescription.Equals(other.ErrorDescription)
                ) && 
                (
                    this.IsSystemError == other.IsSystemError ||
                    this.IsSystemError != null &&
                    this.IsSystemError.Equals(other.IsSystemError)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ErrorCode != null)
                    hash = hash * 59 + this.ErrorCode.GetHashCode();
                if (this.PublicErrorCode != null)
                    hash = hash * 59 + this.PublicErrorCode.GetHashCode();
                if (this.ErrorDescription != null)
                    hash = hash * 59 + this.ErrorDescription.GetHashCode();
                if (this.IsSystemError != null)
                    hash = hash * 59 + this.IsSystemError.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
