/* 
 * Docusign Admin API
 *
 * An API for an organization administrator to manage organizations, accounts and users
 *
 * OpenAPI spec version: v2.1
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using DocuSign.Admin.Client;
using DocuSign.Admin.Model;

namespace DocuSign.Admin.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Returns the list of groups in an account.
        /// </summary>
        /// <remarks>
        /// Required scopes: group_read
        /// </remarks>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">The organization ID Guid</param>
        /// <param name="accountId">The account ID Guid</param>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns></returns>
        MemberGroupsResponse GetGroups(Guid? organizationId, Guid? accountId, AccountsApi.GetGroupsOptions options = null);

        /// <summary>
        /// Returns the list of groups in an account.
        /// </summary>
        /// <remarks>
        /// Required scopes: group_read
        /// </remarks>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">The organization ID Guid</param>
        /// <param name="accountId">The account ID Guid</param>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>ApiResponse of </returns>
        ApiResponse<MemberGroupsResponse> GetGroupsWithHttpInfo(Guid? organizationId, Guid? accountId, AccountsApi.GetGroupsOptions options = null);
        /// <summary>
        /// Returns the list of organizations of which the authenticated user is a member.
        /// </summary>
        /// <remarks>
        /// Required scopes: organization_read
        /// </remarks>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns></returns>
        OrganizationsResponse GetOrganizations(AccountsApi.GetOrganizationsOptions options = null);

        /// <summary>
        /// Returns the list of organizations of which the authenticated user is a member.
        /// </summary>
        /// <remarks>
        /// Required scopes: organization_read
        /// </remarks>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>ApiResponse of </returns>
        ApiResponse<OrganizationsResponse> GetOrganizationsWithHttpInfo(AccountsApi.GetOrganizationsOptions options = null);
        /// <summary>
        /// Returns the list of permission profiles in an account.
        /// </summary>
        /// <remarks>
        /// Required scopes: permission_read
        /// </remarks>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">The organization ID Guid</param>
        /// <param name="accountId">The account ID Guid</param>
        /// <returns></returns>
        PermissionsResponse GetPermissions(Guid? organizationId, Guid? accountId);

        /// <summary>
        /// Returns the list of permission profiles in an account.
        /// </summary>
        /// <remarks>
        /// Required scopes: permission_read
        /// </remarks>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">The organization ID Guid</param>
        /// <param name="accountId">The account ID Guid</param>
        /// <returns>ApiResponse of </returns>
        ApiResponse<PermissionsResponse> GetPermissionsWithHttpInfo(Guid? organizationId, Guid? accountId);
        /// <summary>
        /// Redacts membership data for users with memberships in an account.
        /// </summary>
        /// <remarks>
        /// Required scopes: user_data_redact
        /// </remarks>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The account ID Guid</param>
        /// <param name="requestModel">The request body describing the membership to be redacted</param>
        /// <returns></returns>
        IndividualUserDataRedactionResponse RedactIndividualMembershipData(Guid? accountId, IndividualMembershipDataRedactionRequest requestModel);

        /// <summary>
        /// Redacts membership data for users with memberships in an account.
        /// </summary>
        /// <remarks>
        /// Required scopes: user_data_redact
        /// </remarks>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The account ID Guid</param>
        /// <param name="requestModel">The request body describing the membership to be redacted</param>
        /// <returns>ApiResponse of </returns>
        ApiResponse<IndividualUserDataRedactionResponse> RedactIndividualMembershipDataWithHttpInfo(Guid? accountId, IndividualMembershipDataRedactionRequest requestModel);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Returns the list of groups in an account.
        /// </summary>
        /// <remarks>
        /// Required scopes: group_read
        /// </remarks>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">The organization ID Guid</param>
        /// <param name="accountId">The account ID Guid</param>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>Task of MemberGroupsResponse</returns>
        System.Threading.Tasks.Task<MemberGroupsResponse> GetGroupsAsync(Guid? organizationId, Guid? accountId, AccountsApi.GetGroupsOptions options = null);

        /// <summary>
        /// Returns the list of groups in an account.
        /// </summary>
        /// <remarks>
        /// Required scopes: group_read
        /// </remarks>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">The organization ID Guid</param>
        /// <param name="accountId">The account ID Guid</param>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>Task of ApiResponse (MemberGroupsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MemberGroupsResponse>> GetGroupsAsyncWithHttpInfo(Guid? organizationId, Guid? accountId, AccountsApi.GetGroupsOptions options = null);
        /// <summary>
        /// Returns the list of organizations of which the authenticated user is a member.
        /// </summary>
        /// <remarks>
        /// Required scopes: organization_read
        /// </remarks>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>Task of OrganizationsResponse</returns>
        System.Threading.Tasks.Task<OrganizationsResponse> GetOrganizationsAsync(AccountsApi.GetOrganizationsOptions options = null);

        /// <summary>
        /// Returns the list of organizations of which the authenticated user is a member.
        /// </summary>
        /// <remarks>
        /// Required scopes: organization_read
        /// </remarks>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>Task of ApiResponse (OrganizationsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<OrganizationsResponse>> GetOrganizationsAsyncWithHttpInfo(AccountsApi.GetOrganizationsOptions options = null);
        /// <summary>
        /// Returns the list of permission profiles in an account.
        /// </summary>
        /// <remarks>
        /// Required scopes: permission_read
        /// </remarks>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">The organization ID Guid</param>
        /// <param name="accountId">The account ID Guid</param>
        /// <returns>Task of PermissionsResponse</returns>
        System.Threading.Tasks.Task<PermissionsResponse> GetPermissionsAsync(Guid? organizationId, Guid? accountId);

        /// <summary>
        /// Returns the list of permission profiles in an account.
        /// </summary>
        /// <remarks>
        /// Required scopes: permission_read
        /// </remarks>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">The organization ID Guid</param>
        /// <param name="accountId">The account ID Guid</param>
        /// <returns>Task of ApiResponse (PermissionsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PermissionsResponse>> GetPermissionsAsyncWithHttpInfo(Guid? organizationId, Guid? accountId);
        /// <summary>
        /// Redacts membership data for users with memberships in an account.
        /// </summary>
        /// <remarks>
        /// Required scopes: user_data_redact
        /// </remarks>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The account ID Guid</param>
        /// <param name="requestModel">The request body describing the membership to be redacted</param>
        /// <returns>Task of IndividualUserDataRedactionResponse</returns>
        System.Threading.Tasks.Task<IndividualUserDataRedactionResponse> RedactIndividualMembershipDataAsync(Guid? accountId, IndividualMembershipDataRedactionRequest requestModel);

        /// <summary>
        /// Redacts membership data for users with memberships in an account.
        /// </summary>
        /// <remarks>
        /// Required scopes: user_data_redact
        /// </remarks>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The account ID Guid</param>
        /// <param name="requestModel">The request body describing the membership to be redacted</param>
        /// <returns>Task of ApiResponse (IndividualUserDataRedactionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<IndividualUserDataRedactionResponse>> RedactIndividualMembershipDataAsyncWithHttpInfo(Guid? accountId, IndividualMembershipDataRedactionRequest requestModel);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AccountsApi : IAccountsApi
    {
        private DocuSign.Admin.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountsApi"/> class
        /// using AplClient object
        /// </summary>
        /// <param name="aplClient">An instance of AplClient</param>
        /// <returns></returns>
        public AccountsApi(DocuSignClient aplClient)
        {
            this.ApiClient = aplClient;

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.ApiClient.GetBasePath();
        }

        /// <summary>
        /// Gets or sets the ApiClient object
        /// </summary>
        /// <value>An instance of the ApiClient</value>
        public DocuSignClient ApiClient { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public DocuSign.Admin.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Returns the list of groups in an account. Required scopes: group_read
        /// </summary>
        public class GetGroupsOptions
        {
            /// Index of first item to include in the response  Default value: 0 
            public int? start {get; set;}
            /// Page size of the response  Default value: 20 
            public int? take {get; set;}
            /// Index of the last item to include in the response. Ignored if &#39;take&#39; parameter is specfied 
            public int? end {get; set;}
        }

        /// <summary>
        /// Returns the list of groups in an account. Required scopes: group_read
        /// </summary>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">The organization ID Guid</param>
        /// <param name="accountId">The account ID Guid</param>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>MemberGroupsResponse</returns>
        public MemberGroupsResponse GetGroups(Guid? organizationId, Guid? accountId, AccountsApi.GetGroupsOptions options = null)
        {
             ApiResponse<MemberGroupsResponse> localVarResponse = GetGroupsWithHttpInfo(organizationId, accountId, options);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns the list of groups in an account. Required scopes: group_read
        /// </summary>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">The organization ID Guid</param>
        /// <param name="accountId">The account ID Guid</param>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>ApiResponse of MemberGroupsResponse</returns>
        public ApiResponse<MemberGroupsResponse> GetGroupsWithHttpInfo(Guid? organizationId, Guid? accountId, AccountsApi.GetGroupsOptions options = null)
        {
            // verify the required parameter 'organizationId' is set
            if (organizationId == null)
                throw new ApiException(400, "Missing required parameter 'organizationId' when calling AccountsApi->GetGroups");
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling AccountsApi->GetGroups");

            var localVarPath = "/v2/organizations/{organizationId}/accounts/{accountId}/groups";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(this.ApiClient.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new List<FileParameter>();
            Object localVarPostBody = null;
            String localVarHttpContentDisposition = string.Empty;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (organizationId != null) localVarPathParams.Add("organizationId", this.ApiClient.ParameterToString(organizationId)); // path parameter
            if (accountId != null) localVarPathParams.Add("accountId", this.ApiClient.ParameterToString(accountId)); // path parameter
            if (options != null)
            {
                if (options.start != null) localVarQueryParams.Add("start", this.ApiClient.ParameterToString(options.start)); // query parameter
                if (options.take != null) localVarQueryParams.Add("take", this.ApiClient.ParameterToString(options.take)); // query parameter
                if (options.end != null) localVarQueryParams.Add("end", this.ApiClient.ParameterToString(options.end)); // query parameter
            }

            // authentication (docusignAccessCode) required
            // oauth required
            if (!String.IsNullOrEmpty(this.ApiClient.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.ApiClient.Configuration.AccessToken;
            }


            // make the HTTP request
            DocuSignRequest localVarRequest = this.ApiClient.PrepareRequest(localVarPath, new HttpMethod("GET"), localVarQueryParams.ToList(), localVarPostBody, localVarHeaderParams.ToList(), localVarFormParams.ToList(), localVarPathParams.ToList(), localVarFileParams, localVarHttpContentType, localVarHttpContentDisposition);
            DocuSignResponse localVarResponse = this.ApiClient.CallApi(localVarRequest);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetGroups", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MemberGroupsResponse>(localVarStatusCode, 
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()), 
                (MemberGroupsResponse)this.ApiClient.Deserialize(localVarResponse, typeof(MemberGroupsResponse)));
        }

        /// <summary>
        /// Returns the list of groups in an account. Required scopes: group_read
        /// </summary>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">The organization ID Guid</param>
        /// <param name="accountId">The account ID Guid</param>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>Task of MemberGroupsResponse</returns>
        public async System.Threading.Tasks.Task<MemberGroupsResponse> GetGroupsAsync(Guid? organizationId, Guid? accountId, AccountsApi.GetGroupsOptions options = null)
        {
             ApiResponse<MemberGroupsResponse> localVarResponse = await GetGroupsAsyncWithHttpInfo(organizationId, accountId, options);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns the list of groups in an account. Required scopes: group_read
        /// </summary>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">The organization ID Guid</param>
        /// <param name="accountId">The account ID Guid</param>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>Task of ApiResponse (MemberGroupsResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MemberGroupsResponse>> GetGroupsAsyncWithHttpInfo(Guid? organizationId, Guid? accountId, AccountsApi.GetGroupsOptions options = null)
        {
            // verify the required parameter 'organizationId' is set
            if (organizationId == null)
                throw new ApiException(400, "Missing required parameter 'organizationId' when calling AccountsApi->GetGroups");
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling AccountsApi->GetGroups");

            var localVarPath = "/v2/organizations/{organizationId}/accounts/{accountId}/groups";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(this.ApiClient.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new List<FileParameter>();
            Object localVarPostBody = null;
            String localVarHttpContentDisposition = string.Empty;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (organizationId != null) localVarPathParams.Add("organizationId", this.ApiClient.ParameterToString(organizationId)); // path parameter
            if (accountId != null) localVarPathParams.Add("accountId", this.ApiClient.ParameterToString(accountId)); // path parameter
            if (options != null)
            {
                if (options.start != null) localVarQueryParams.Add("start", this.ApiClient.ParameterToString(options.start)); // query parameter
                if (options.take != null) localVarQueryParams.Add("take", this.ApiClient.ParameterToString(options.take)); // query parameter
                if (options.end != null) localVarQueryParams.Add("end", this.ApiClient.ParameterToString(options.end)); // query parameter
            }

            // authentication (docusignAccessCode) required
            // oauth required
            if (!String.IsNullOrEmpty(this.ApiClient.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.ApiClient.Configuration.AccessToken;
            }


            // make the HTTP request
            DocuSignRequest localVarRequest = this.ApiClient.PrepareRequest(localVarPath, new HttpMethod("GET"), localVarQueryParams.ToList(), localVarPostBody, localVarHeaderParams.ToList(), localVarFormParams.ToList(), localVarPathParams.ToList(), localVarFileParams, localVarHttpContentType, localVarHttpContentDisposition);
            DocuSignResponse localVarResponse = await this.ApiClient.CallApiAsync(localVarRequest);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetGroups", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MemberGroupsResponse>(localVarStatusCode, 
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()), 
                (MemberGroupsResponse)this.ApiClient.Deserialize(localVarResponse, typeof(MemberGroupsResponse)));
        }

        /// <summary>
        /// Returns the list of organizations of which the authenticated user is a member. Required scopes: organization_read
        /// </summary>
        public class GetOrganizationsOptions
        {
            /// Specifies how to select the organizations. Values: org_admin - will return organizations for which the user is an admin; account_membership: will return organizations that contain an account of which the user is a member  Default value: org_admin 
            public string mode {get; set;}
        }

        /// <summary>
        /// Returns the list of organizations of which the authenticated user is a member. Required scopes: organization_read
        /// </summary>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>OrganizationsResponse</returns>
        public OrganizationsResponse GetOrganizations(AccountsApi.GetOrganizationsOptions options = null)
        {
             ApiResponse<OrganizationsResponse> localVarResponse = GetOrganizationsWithHttpInfo(options);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns the list of organizations of which the authenticated user is a member. Required scopes: organization_read
        /// </summary>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>ApiResponse of OrganizationsResponse</returns>
        public ApiResponse<OrganizationsResponse> GetOrganizationsWithHttpInfo(AccountsApi.GetOrganizationsOptions options = null)
        {

            var localVarPath = "/v2/organizations";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(this.ApiClient.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new List<FileParameter>();
            Object localVarPostBody = null;
            String localVarHttpContentDisposition = string.Empty;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (options != null)
            {
                if (options.mode != null) localVarQueryParams.Add("mode", this.ApiClient.ParameterToString(options.mode)); // query parameter
            }

            // authentication (docusignAccessCode) required
            // oauth required
            if (!String.IsNullOrEmpty(this.ApiClient.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.ApiClient.Configuration.AccessToken;
            }


            // make the HTTP request
            DocuSignRequest localVarRequest = this.ApiClient.PrepareRequest(localVarPath, new HttpMethod("GET"), localVarQueryParams.ToList(), localVarPostBody, localVarHeaderParams.ToList(), localVarFormParams.ToList(), localVarPathParams.ToList(), localVarFileParams, localVarHttpContentType, localVarHttpContentDisposition);
            DocuSignResponse localVarResponse = this.ApiClient.CallApi(localVarRequest);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetOrganizations", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OrganizationsResponse>(localVarStatusCode, 
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()), 
                (OrganizationsResponse)this.ApiClient.Deserialize(localVarResponse, typeof(OrganizationsResponse)));
        }

        /// <summary>
        /// Returns the list of organizations of which the authenticated user is a member. Required scopes: organization_read
        /// </summary>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>Task of OrganizationsResponse</returns>
        public async System.Threading.Tasks.Task<OrganizationsResponse> GetOrganizationsAsync(AccountsApi.GetOrganizationsOptions options = null)
        {
             ApiResponse<OrganizationsResponse> localVarResponse = await GetOrganizationsAsyncWithHttpInfo(options);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns the list of organizations of which the authenticated user is a member. Required scopes: organization_read
        /// </summary>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="options">Options for modifying the behavior of the function.</param>
        /// <returns>Task of ApiResponse (OrganizationsResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<OrganizationsResponse>> GetOrganizationsAsyncWithHttpInfo(AccountsApi.GetOrganizationsOptions options = null)
        {

            var localVarPath = "/v2/organizations";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(this.ApiClient.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new List<FileParameter>();
            Object localVarPostBody = null;
            String localVarHttpContentDisposition = string.Empty;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (options != null)
            {
                if (options.mode != null) localVarQueryParams.Add("mode", this.ApiClient.ParameterToString(options.mode)); // query parameter
            }

            // authentication (docusignAccessCode) required
            // oauth required
            if (!String.IsNullOrEmpty(this.ApiClient.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.ApiClient.Configuration.AccessToken;
            }


            // make the HTTP request
            DocuSignRequest localVarRequest = this.ApiClient.PrepareRequest(localVarPath, new HttpMethod("GET"), localVarQueryParams.ToList(), localVarPostBody, localVarHeaderParams.ToList(), localVarFormParams.ToList(), localVarPathParams.ToList(), localVarFileParams, localVarHttpContentType, localVarHttpContentDisposition);
            DocuSignResponse localVarResponse = await this.ApiClient.CallApiAsync(localVarRequest);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetOrganizations", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OrganizationsResponse>(localVarStatusCode, 
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()), 
                (OrganizationsResponse)this.ApiClient.Deserialize(localVarResponse, typeof(OrganizationsResponse)));
        }


        /// <summary>
        /// Returns the list of permission profiles in an account. Required scopes: permission_read
        /// </summary>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">The organization ID Guid</param>
        /// <param name="accountId">The account ID Guid</param>
        /// <returns>PermissionsResponse</returns>
        public PermissionsResponse GetPermissions(Guid? organizationId, Guid? accountId)
        {
             ApiResponse<PermissionsResponse> localVarResponse = GetPermissionsWithHttpInfo(organizationId, accountId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns the list of permission profiles in an account. Required scopes: permission_read
        /// </summary>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">The organization ID Guid</param>
        /// <param name="accountId">The account ID Guid</param>
        /// <returns>ApiResponse of PermissionsResponse</returns>
        public ApiResponse<PermissionsResponse> GetPermissionsWithHttpInfo(Guid? organizationId, Guid? accountId)
        {
            // verify the required parameter 'organizationId' is set
            if (organizationId == null)
                throw new ApiException(400, "Missing required parameter 'organizationId' when calling AccountsApi->GetPermissions");
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling AccountsApi->GetPermissions");

            var localVarPath = "/v2/organizations/{organizationId}/accounts/{accountId}/permissions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(this.ApiClient.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new List<FileParameter>();
            Object localVarPostBody = null;
            String localVarHttpContentDisposition = string.Empty;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (organizationId != null) localVarPathParams.Add("organizationId", this.ApiClient.ParameterToString(organizationId)); // path parameter
            if (accountId != null) localVarPathParams.Add("accountId", this.ApiClient.ParameterToString(accountId)); // path parameter

            // authentication (docusignAccessCode) required
            // oauth required
            if (!String.IsNullOrEmpty(this.ApiClient.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.ApiClient.Configuration.AccessToken;
            }


            // make the HTTP request
            DocuSignRequest localVarRequest = this.ApiClient.PrepareRequest(localVarPath, new HttpMethod("GET"), localVarQueryParams.ToList(), localVarPostBody, localVarHeaderParams.ToList(), localVarFormParams.ToList(), localVarPathParams.ToList(), localVarFileParams, localVarHttpContentType, localVarHttpContentDisposition);
            DocuSignResponse localVarResponse = this.ApiClient.CallApi(localVarRequest);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetPermissions", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PermissionsResponse>(localVarStatusCode, 
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()), 
                (PermissionsResponse)this.ApiClient.Deserialize(localVarResponse, typeof(PermissionsResponse)));
        }

        /// <summary>
        /// Returns the list of permission profiles in an account. Required scopes: permission_read
        /// </summary>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">The organization ID Guid</param>
        /// <param name="accountId">The account ID Guid</param>
        /// <returns>Task of PermissionsResponse</returns>
        public async System.Threading.Tasks.Task<PermissionsResponse> GetPermissionsAsync(Guid? organizationId, Guid? accountId)
        {
             ApiResponse<PermissionsResponse> localVarResponse = await GetPermissionsAsyncWithHttpInfo(organizationId, accountId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns the list of permission profiles in an account. Required scopes: permission_read
        /// </summary>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">The organization ID Guid</param>
        /// <param name="accountId">The account ID Guid</param>
        /// <returns>Task of ApiResponse (PermissionsResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PermissionsResponse>> GetPermissionsAsyncWithHttpInfo(Guid? organizationId, Guid? accountId)
        {
            // verify the required parameter 'organizationId' is set
            if (organizationId == null)
                throw new ApiException(400, "Missing required parameter 'organizationId' when calling AccountsApi->GetPermissions");
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling AccountsApi->GetPermissions");

            var localVarPath = "/v2/organizations/{organizationId}/accounts/{accountId}/permissions";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(this.ApiClient.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new List<FileParameter>();
            Object localVarPostBody = null;
            String localVarHttpContentDisposition = string.Empty;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (organizationId != null) localVarPathParams.Add("organizationId", this.ApiClient.ParameterToString(organizationId)); // path parameter
            if (accountId != null) localVarPathParams.Add("accountId", this.ApiClient.ParameterToString(accountId)); // path parameter

            // authentication (docusignAccessCode) required
            // oauth required
            if (!String.IsNullOrEmpty(this.ApiClient.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.ApiClient.Configuration.AccessToken;
            }


            // make the HTTP request
            DocuSignRequest localVarRequest = this.ApiClient.PrepareRequest(localVarPath, new HttpMethod("GET"), localVarQueryParams.ToList(), localVarPostBody, localVarHeaderParams.ToList(), localVarFormParams.ToList(), localVarPathParams.ToList(), localVarFileParams, localVarHttpContentType, localVarHttpContentDisposition);
            DocuSignResponse localVarResponse = await this.ApiClient.CallApiAsync(localVarRequest);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetPermissions", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PermissionsResponse>(localVarStatusCode, 
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()), 
                (PermissionsResponse)this.ApiClient.Deserialize(localVarResponse, typeof(PermissionsResponse)));
        }


        /// <summary>
        /// Redacts membership data for users with memberships in an account. Required scopes: user_data_redact
        /// </summary>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The account ID Guid</param>
        /// <param name="requestModel">The request body describing the membership to be redacted</param>
        /// <returns>IndividualUserDataRedactionResponse</returns>
        public IndividualUserDataRedactionResponse RedactIndividualMembershipData(Guid? accountId, IndividualMembershipDataRedactionRequest requestModel)
        {
             ApiResponse<IndividualUserDataRedactionResponse> localVarResponse = RedactIndividualMembershipDataWithHttpInfo(accountId, requestModel);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Redacts membership data for users with memberships in an account. Required scopes: user_data_redact
        /// </summary>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The account ID Guid</param>
        /// <param name="requestModel">The request body describing the membership to be redacted</param>
        /// <returns>ApiResponse of IndividualUserDataRedactionResponse</returns>
        public ApiResponse<IndividualUserDataRedactionResponse> RedactIndividualMembershipDataWithHttpInfo(Guid? accountId, IndividualMembershipDataRedactionRequest requestModel)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling AccountsApi->RedactIndividualMembershipData");
            // verify the required parameter 'requestModel' is set
            if (requestModel == null)
                throw new ApiException(400, "Missing required parameter 'requestModel' when calling AccountsApi->RedactIndividualMembershipData");

            var localVarPath = "/v2/data_redaction/accounts/{accountId}/user";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(this.ApiClient.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new List<FileParameter>();
            Object localVarPostBody = null;
            String localVarHttpContentDisposition = string.Empty;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", this.ApiClient.ParameterToString(accountId)); // path parameter
            if (requestModel != null && requestModel.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.ApiClient.Serialize(requestModel); // http body (model) parameter
            }
            else
            {
                localVarPostBody = requestModel; // byte array
            }

            // authentication (docusignAccessCode) required
            // oauth required
            if (!String.IsNullOrEmpty(this.ApiClient.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.ApiClient.Configuration.AccessToken;
            }


            // make the HTTP request
            DocuSignRequest localVarRequest = this.ApiClient.PrepareRequest(localVarPath, new HttpMethod("POST"), localVarQueryParams.ToList(), localVarPostBody, localVarHeaderParams.ToList(), localVarFormParams.ToList(), localVarPathParams.ToList(), localVarFileParams, localVarHttpContentType, localVarHttpContentDisposition);
            DocuSignResponse localVarResponse = this.ApiClient.CallApi(localVarRequest);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RedactIndividualMembershipData", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<IndividualUserDataRedactionResponse>(localVarStatusCode, 
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()), 
                (IndividualUserDataRedactionResponse)this.ApiClient.Deserialize(localVarResponse, typeof(IndividualUserDataRedactionResponse)));
        }

        /// <summary>
        /// Redacts membership data for users with memberships in an account. Required scopes: user_data_redact
        /// </summary>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The account ID Guid</param>
        /// <param name="requestModel">The request body describing the membership to be redacted</param>
        /// <returns>Task of IndividualUserDataRedactionResponse</returns>
        public async System.Threading.Tasks.Task<IndividualUserDataRedactionResponse> RedactIndividualMembershipDataAsync(Guid? accountId, IndividualMembershipDataRedactionRequest requestModel)
        {
             ApiResponse<IndividualUserDataRedactionResponse> localVarResponse = await RedactIndividualMembershipDataAsyncWithHttpInfo(accountId, requestModel);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Redacts membership data for users with memberships in an account. Required scopes: user_data_redact
        /// </summary>
        /// <exception cref="DocuSign.Admin.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">The account ID Guid</param>
        /// <param name="requestModel">The request body describing the membership to be redacted</param>
        /// <returns>Task of ApiResponse (IndividualUserDataRedactionResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<IndividualUserDataRedactionResponse>> RedactIndividualMembershipDataAsyncWithHttpInfo(Guid? accountId, IndividualMembershipDataRedactionRequest requestModel)
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
                throw new ApiException(400, "Missing required parameter 'accountId' when calling AccountsApi->RedactIndividualMembershipData");
            // verify the required parameter 'requestModel' is set
            if (requestModel == null)
                throw new ApiException(400, "Missing required parameter 'requestModel' when calling AccountsApi->RedactIndividualMembershipData");

            var localVarPath = "/v2/data_redaction/accounts/{accountId}/user";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(this.ApiClient.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new List<FileParameter>();
            Object localVarPostBody = null;
            String localVarHttpContentDisposition = string.Empty;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (accountId != null) localVarPathParams.Add("accountId", this.ApiClient.ParameterToString(accountId)); // path parameter
            if (requestModel != null && requestModel.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.ApiClient.Serialize(requestModel); // http body (model) parameter
            }
            else
            {
                localVarPostBody = requestModel; // byte array
            }

            // authentication (docusignAccessCode) required
            // oauth required
            if (!String.IsNullOrEmpty(this.ApiClient.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.ApiClient.Configuration.AccessToken;
            }


            // make the HTTP request
            DocuSignRequest localVarRequest = this.ApiClient.PrepareRequest(localVarPath, new HttpMethod("POST"), localVarQueryParams.ToList(), localVarPostBody, localVarHeaderParams.ToList(), localVarFormParams.ToList(), localVarPathParams.ToList(), localVarFileParams, localVarHttpContentType, localVarHttpContentDisposition);
            DocuSignResponse localVarResponse = await this.ApiClient.CallApiAsync(localVarRequest);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RedactIndividualMembershipData", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<IndividualUserDataRedactionResponse>(localVarStatusCode, 
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()), 
                (IndividualUserDataRedactionResponse)this.ApiClient.Deserialize(localVarResponse, typeof(IndividualUserDataRedactionResponse)));
        }

    }
}